### ISSUE TITLE
Not published on NPM

### ISSUE THREAD

**Issue by mozfet** [makandra/superclamp#1]
Hi, nice package, want to try it out. Installation instructions mention npm, plus there is a settings.json all ready... so I try:

```
npm install --save superclamp
```

but npm gives error:
```
npm ERR! code E404
npm ERR! 404 Not Found: superclamp@latest
```

**Comment by mozfet** [comment]
On the other hand the package works a charm from github, and npm can install from git repos. Thanks, package works like a charm for me, none of the other libs I tried worked, this was number 6!

**Comment by foobear** [comment]
Thanks for the reminder! Package has now been published on npm: https://www.npmjs.com/package/superclamp

:cake:
